name: CMake

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Hello
      run: echo "Hello"
      
    - name: input build dir
      run: cd ${{github.workspace}}/build
      
    - name: building
      run: cd ${{github.workspace}}/build; echo $(pwd); sh build.sh demo
      
    - name: delete file
      run: rm -rf ${{github.workspace}}/build/demo

    - name: input MyNotion dir
      run: ls -l ${{github.workspace}}/build/product/bin

    - name: show MyNotion
      run: ls -l ${{github.workspace}}/build/product/lib

    - name: run MyNotion
      run: ${{github.workspace}}/build/product/bin/MyNotion

    - name: Over
      run: echo "Over"
    
#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       run: ctest -C ${{env.BUILD_TYPE}}
      
