name: CMake

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Hello
      run: echo "Hello"
      run: echo "Hello123"
      
    - name: input build dir
      run: ${{github.workspace}}/build
      
    - name: cmake:building
      run: cmake ..
      
    - name: make:building
      run: make
      
    - name: Over
      run: echo "Over"
    
#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       run: ctest -C ${{env.BUILD_TYPE}}
      
