name: CMake

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Hello
      run: echo "Hello"
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: BuildCmake
      run: cmake --build ${{github.workspace}}/build
      
    - name: Building
      run: ./${{github.workspace}}/build/make

#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       run: ctest -C ${{env.BUILD_TYPE}}
      
