name: CMake

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Hello
      run: echo "Hello"
      
    - name: Configure CMake
      run: cd ${{github.workspace}}/build&&$(cmake ..)
      
    - name: Building
      run: ./${{github.workspace}}/build/make
      
    - name: Over
      run: echo "Over"
    
#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       run: ctest -C ${{env.BUILD_TYPE}}
      
