name: CMake

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Hello
      run: echo "Hello"
      
    - name: input build dir
      run: cd ${{github.workspace}}/build
      
    - name: building
      run: sh build.sh demo
      
    - name: delete file
      run: rm -rf ./demo

    -name: input MyNotion dir
      run: ls -l ${{github.workspace}}/build/product/lib/bin
      
    -name: show MyNotion
      run: ls -l ${{github.workspace}}/build/product/lib/lib

    - name: Over
      run: echo "Over"
    
#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       run: ctest -C ${{env.BUILD_TYPE}}
      
